#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nitrogen --restore &
~/.config/polybar/launch.sh

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
	xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --left-of eDP-1
fi

# Workspaces
bspc monitor -d I II III IV V

# Extra
bspc config border_width         2
bspc config window_gap          16
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Seems useless
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
